<form class="quote_status_form" action="generate_quotation_landingpage.php" method="POST" autocomplete="off">
    <div class="stat_container">
        <div class="icon_container">
            <p>Quotation Status</p>
            <span class="back_icon" onclick="goBack()">X</span>
        </div>

        <div class="trial1">
            <input type="text" name="stats_ref_no" placeholder="" value="<?php echo htmlspecialchars($row['ref_no']); ?>" class="input02" readonly>
            <label class="placeholder2">Ref No</label>
        </div>
        
        <input type="hidden" name="stats_compname" value="<?php echo htmlspecialchars($companyname001); ?>">
        
        <div class="trial1">
            <input type="text" name="generated_By" placeholder="" value="<?php echo htmlspecialchars($row['sender_name']); ?>" class="input02" readonly>
            <label class="placeholder2">Generated By</label>
        </div>
        
        <div class="trial1">
            <select name="current_status_" id="status_dd" class="input02" onchange="current_status()" required>
                <option value="" disabled selected>Current Status</option>
                <option value="Inquiry Closed">Inquiry Closed</option>
                <option value="Open">Open</option>
                <option value="Regretted">Regretted</option>
                <option value="Won">Won</option>
                <option value="Lost">Lost</option>
            </select>
        </div>
        
        <div class="trial1" id="enquiry_closed_dd" style="display: none;">
            <select name="enquiry_close" id="enquiry_reason" class="input02" onchange="enquiry_info()">
                <option value="" disabled selected>Inquiry Closed Reason</option>
                <option value="Required Equipment Changed">Required Equipment Changed</option>
                <option value="Requirement Postponed">Requirement Postponed</option>
                <option value="Project Issue">Project Issue</option>
            </select>
        </div>
        
        <div class="trial1" id="postponed_to_" style="display: none;">
            <input type="date" name="postponed_date" placeholder="" class="input02">
            <label class="placeholder2">Postponed Date</label>
        </div>
        
        <div class="trial1" id="lost_to_" style="display: none;">
            <input type="text" name="lost_to" placeholder="" class="input02">
            <label class="placeholder2">Lost To ?</label>
        </div>
        
        <div class="trial1" id="regretted_reason_" style="display: none;">
            <select name="regretted_reason" id="regret_reason_dd" class="input02">
                <option value="" disabled selected>Regretted Reason</option>
                <option value="Price Issue">Price Issue</option>
                <option value="Equipment Not Available">Equipment Not Available</option>
                <option value="Other Issue">Other Issue</option>
            </select>
        </div>
        
        <button class="basic-detail-button" id="quote_submit_button" type="submit" name="quote_status_btn">Submit</button>
    </div>
</form>
